baseURL: "https://chan-dong-jun.github.io/"
languageCode: en-us
title: test
theme: hugo-PaperMod


# Home info mode
params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "<platform>"
            url: "<link>"
        - name: "<platform 2>"
            url: "<link2>"